version: '2'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - $PWD/database/data:/var/lib/postgresql/data
      - $PWD/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  api:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    restart: always
    environment:
      - SENTRY_DSN=https://f0f3980ec56e4c79986e4e4bdef50bea@o4505519663939584.ingest.sentry.io/4505519664791552
      - EXTERNAL_URL=http://127.0.0.1:40080/app
      - ADMIN_EMAIL=admin@example.com
      - JWT_SECRET_KEY=secret
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TOKEN_JSON=$TOKEN_JSON
      - CREDENTIALS_JSON=$CREDENTIALS_JSON
    volumes:
      - $PWD/backend:/app
  export:
    build: export
    depends_on:
      - db
      - api
    restart: always
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - ADMIN_EMAIL=admin@example.com
      - JWT_SECRET_KEY=secret
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CLIENT_SECRET_JSON=$CLIENT_SECRET_JSON
    volumes:
      - $PWD/export/main.py:/app/main.py
      - $PWD/export/utils.py:/app/utils.py
  frontend:
    build: frontend
    depends_on:
      - api
    restart: always
    ports:
      - "0.0.0.0:40080:80"
    volumes:
      - $PWD/frontend/html:/usr/share/nginx/html

