version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    container_name: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - $PWD/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
