{
 "title": "STATS",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "<div data-testid=\"TextPanel-converted-content\" class=\"markdown-html css-fb3dw2\" style=\"display: flex; justify-content: center; align-items: center; height: 100%;\">\n  <h3 style=\"text-align: center\">Statistiques<br><br>🏓 TOURNOI NATIONAL B DE L’E.P. LOGNES 🏓 - 21 décembre et 22 décembre 2024</h3>\n</div>\n"
   }
  },
  {
   "title": "Total inscrits",
   "type": "stat",
   "description": "liste d'attente comprise",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT m.id) AS num_members_with_confirmed_entries\nFROM members AS m\nWHERE EXISTS (\n    SELECT 1\n    FROM entries AS e\n    WHERE e.member_id = m.id\n    AND e.confirmed = 't' -- At least one entry with confirmed = true\n    AND e.deleted_at IS NULL -- At least one entry with deleted_at IS NULL\n)"
    }
   ]
  },
  {
   "title": "Inscrits",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT m.points, m.last_name || ' ' || m.first_name AS name, m.club_name AS club\nFROM members AS m\nWHERE EXISTS (\n    SELECT 1\n    FROM entries AS e\n    WHERE e.member_id = m.id\n    AND e.confirmed = 't' -- At least one entry with confirmed = true\n    AND e.deleted_at IS NULL -- At least one entry with deleted_at IS NULL\n)\nORDER BY m.points DESC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": {
    "content": "<div data-testid=\"TextPanel-converted-content\" class=\"markdown-html css-fb3dw2\" style=\"display: flex; justify-content: center; align-items: center; height: 100%;\">\n  <img src=\"https://tournoi.app.lognestt.fr/img/2024-12-band-day-1.png\">\n</div>\n"
   }
  },
  {
   "title": "Remplissage des tableaux Samedi",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT b.name AS band_name, COUNT(e.id) AS \"Nombre d'inscrits\", b.max_entries AS \"Places Maxi\"\nFROM bands b\nLEFT JOIN entries e ON b.id = e.band_id\nWHERE e.confirmed = 't' AND e.deleted_at IS NULL AND b.day = 1\nGROUP BY b.name, b.max_entries, b.created_at\nORDER BY MIN(b.created_at);\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": {
    "content": "<div data-testid=\"TextPanel-converted-content\" class=\"markdown-html css-fb3dw2\" style=\"display: flex; justify-content: center; align-items: center; height: 100%;\">\n  <img src=\"https://tournoi.app.lognestt.fr/img/2024-12-band-day-2.png\">\n</div>\n"
   }
  },
  {
   "title": "Remplissage des tableaux Dimanche",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 8, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT b.name AS band_name, COUNT(e.id) AS \"Nombre d'inscrits\", b.max_entries AS \"Places Maxi\"\nFROM bands b\nLEFT JOIN entries e ON b.id = e.band_id\nWHERE e.confirmed = 't' AND e.deleted_at IS NULL AND b.day = 2\nGROUP BY b.name, b.max_entries, b.created_at\nORDER BY MIN(b.created_at);\n"
    }
   ]
  },
  {
   "title": "Inscrits par club",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS club_count, club_name\nFROM members\nGROUP BY club_name\nORDER BY club_count DESC\n\n"
    }
   ]
  },
  {
   "title": "Places restantes (Tableau | Nombre)",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT b.name AS \"Tableau\", \n       b.max_entries - COUNT(e.id) AS \"Places Restantes\"\nFROM bands b\nLEFT JOIN entries e ON b.id = e.band_id\nWHERE e.confirmed = 't' AND e.deleted_at IS NULL\nGROUP BY b.name, b.max_entries\nHAVING b.max_entries - COUNT(e.id) > 0\nORDER BY MIN(b.created_at);\n"
    }
   ]
  },
  {
   "title": "Nombre de tableaux inscrits par inscription",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT num_entries_per_member::text, COUNT(*) AS num_entries\nFROM (\n  SELECT member_id, COUNT(*) AS num_entries_per_member\n  FROM entries\n  WHERE confirmed = 't' AND deleted_at IS NULL\n  GROUP BY member_id\n) AS member_entry_counts\nGROUP BY num_entries_per_member\nORDER BY num_entries_per_member;\n"
    }
   ]
  }
 ]
}